// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/channels/eve.ts";
import * as module_2 from "../../agent/channels/whatsapp.ts";
import * as module_3 from "../../agent/tools/confirm-consent.ts";
import * as module_4 from "../../agent/tools/save-check-in.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "channels/eve.ts": module_1,
                  "channels/whatsapp.ts": module_2,
                  "tools/confirm-consent.ts": module_3,
                  "tools/save-check-in.ts": module_4
                })
            })
    })
});

export default moduleMap;
